### ISSUE TITLE
create BM version

### ISSUE THREAD

**Issue by paragasu** [phisoft/sabahruralfarmers-web#36]
https://www.sabahruralfarmers.org/

- [x] duplicate index.html with name index_my.html
- [x] update content to BM
- [x] add language link to top left & bottom page

**Comment by Azieyati** [comment]
@paragasu 

Sekadar idea:
- To place the language link at the bottom left of the page so that the user may easily access the language link in different devices.

[Screen Recording - Made with FlexClip (4).webm](https://github.com/phisoft/sabahruralfarmers-web/assets/156404474/804cb6d3-a170-40c0-94f6-c2d56895fd4d)


But this is the original settings:
- add language link to top left & bottom page
[Screen Recording - Made with FlexClip (3).webm](https://github.com/phisoft/sabahruralfarmers-web/assets/156404474/c4fb373b-2e52-48d7-bda2-0211a8630ed5)
